# -*- coding: utf-8 -*-
"""Python - Loops and Lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfqtRK9o-XkRqkha4B1xa2YgIiW0tvrG

# loops
"""

# for loop

for a in range(1,6):
  print( a , "Hello world ")

for i in range(2,6,2):
  print(i)

n=7
for i in range(1,11):
  print(n,"*",i,"=",n*i)

n=input("enter the number")
n=int(n)
for i in range(1,11):
  print(n,"*",i,"=",n*i)

# while loop

n=0
while n<5:
  print(n)
  n=n+1

n=1
a=4
while n<=10:
  print(a,"*",n,"=",n*a)
  n+=2

# while true
# it is a infinite loop stop y break statement

while True:
  print("hello ")

while True:
  num1 =int(input("Enter a number 1 : "))
  num2 =int(input("Enter a number 2 : "))
  print("sum =",num1+num2 )
  repeat=input("Do you want to stop thr program ? (s/n): ")
  if repeat=="s":
    break

# nested loop
# a loop inside a loop

for i in range (1,4):
  for j in range(1,11):
    print (j,end="")

  print("")

for i in range (1,6):
  for j in range (1,i+1):
    print(i,end=" ")
  print()

# for loop with conditional statement

for i in range (1,11):
  if i==3:
    print("add this number in favs .")
  else :
    print(i)

for i in range (1,100):
  if i%8==0 and i%12==0:
    print(i)

n=1
while n<10:
  if n==3:
    print("add i it in favs")
  else:
    print(n)
  n+=1

"""# Break and  Continue statement"""

# continue statement
# is used when you what to skip a particular condition / iteration

# break statement
# is used to stop the loop

for i in range (1,11):
  if i ==5:
    continue
  print(i)

for i in range (1,11):
  if i==5:
    break
  else:
    print(i)

"""# **Problem Solving**

**write a program to find a sum of all event numbers up to 50**
"""

sum =0
for i in range (1,51):
  if i%2==0:
    sum+=i
print(sum)

"""**write a program to write first numder and their squres number**"""

for i in range (1,21):
  print(i,i**2)

"""**write a program to find sum of first 10 odd numbers using while loop**"""

sum = 0
i=0
while i <=20:
  if i%2!=0:
    sum+=i
  i+=1
print(sum)

"""**write a program to check if a number is divisible by 8 and 12 to 100 numbers**"""

for i in range (1,101):
  if i%8==0 and i%12==0:
    print(i)

"""**write a program to build a biling system at supermarket**"""

while True :
  name=input("Enter costomer's name  :")
  total=0
  while True:
    print("Enter the amount and quantity ")
    amount=int(input("Enter the amount : "))
    quantity=int(input("Enter the quantity : "))
    total+=amount*quantity
    repeat=input("do you want to add more items? (yes/no):")
    if repeat=="no"or repeat =="NO":
      break
  print("-"*40)
  print("Name : ",name)
  print("Total : ",total)

  repeat=input("do you want to add more items? (yes/no):")
  if repeat=="no"or repeat =="NO":
    break

"""**"why fit in, When you are Born to Stand Out "** **a string problem**

**write a program to fnd the lenght of following string**
"""

a="why fit in, When you are Born to Stand Out "
b=len(a)
print("the lenght of given string ",b)

"""**write a program to check how many time alphabet o is occurring**"""

print("the number of time o is occuring ",a.count("o"))

"""**write a program to convert the whole string into lower and uper case**"""

X=a.lower()
print(X)
Y=a.upper()
print(Y)

"""**write a program to convert the following string in to a title**"""

Z=a.title()
print(Z)

"""**write a program to find the index number of " fit in "**"""

print (a.find("fit in"))

"""**1**

---
**1 2**

---
**1 2 3**

---

**1 2 3 4**

---

**1 2 3 4 5**

---

**making this pattren using loop**



"""

for i in range (1,6):
  for j in range (1,i+1):
    print(j,end=" ")
  print( )

"""**1**

---
**2 2**

---
**3 3 3**

---

**4 4 4 4**

---

**5 5 5 5 5**

---

**making this pattren using loop**
"""

for i in range (1,6):
  for j in range (1,i+1):
    print(i,end=" ")
  print( )

for i in range (1,6):
  for j in range (6,i,-1):
    print(i,end=" ")
  print( )

for i in range (1,6):
  for j in range (5,i,-1):
    print(" ",end=" ")
  for k in range (1,i+1):
    print("*",end=" ")
  print( )

for i in range (1,6):
  for j in range (i,0,-1):
    print(j,end=" ")
  print()

for i in range (1,6):
  for j in range (1,i+1):
    print("*",end=" ")
  print()
for i in range (5,0,-1):
  for j in range (0,i-1):
    print("*",end=" ")
  print()

for i in range (1,11):
  for j in range(1,i+1):
    print (i*j,end= " ")
  print("")

"""**write a program to get a fibonacci series upto 10 numbers**"""

# fibonacci seriesa
a=0
b=1
n=int(input("Enter a number : "))
if n==1:
  print(a)
else:
  for  i in range (2,n):
    c=a+b
    a=b
    b=c
    print(c)

"""**write a program to check if a number is prime or not**"""

# prime number
n=int(input("Enter a number : "))
if n>1:
  for i in range (2,n):
    if n%i==0:
      print("not prime")
      break
  else:
    print("prime")
else:
  print("not prime")

"""**write a program to find a palindrome of integers**"""

# palindrome 111 131
n=int(input("Enter a number : "))
temp=n
rev=0
while n>0:
  r=n%10
  rev=rev*10+r
  n=n//10
if temp==rev:
  print("palindrome")
else:
  print("not palindrome")

"""**write a program to create an area caculator**"""

print("******* AERA CALCULATOR ***********")
while True:
  print("press 1 for area of circle")
  print("press 2 for area of rectangle")
  print("press 3 for area of triangle")
  choice=int(input("enter your choice :"))
  if choice==1:
    radius=float(input("enter radius :"))
    area=3.14*radius*radius
    print("area of circle is : ",area)
    print("thank you for using area calculator")

  elif choice==2:
    length=float(input("enter length :"))
    breadth=float(input("enter breadth :"))
    area=length*breadth
    print("area of rectangle is : ",area)
    print("thank you for using area calculator")

  elif choice==3:
    base=float(input("enter base :"))
    height=float(input("enter height :"))
    area=0.5*base*height
    print("area of triangle is : ",area)
  else :
    print("invalid choice")
  choice=input("do you want to continue? (yes/no) :")
  if choice=="no":
    print("thank you for using area calculator")
    break



"""# String  manipulation

lenght, count, upper, lower, index, capitalize, casefold, find, format, center
"""

a="Harry Potter and the Goble of Fire"
print(a)

# lenght
print(len(a)) # space also count

# count find the number oftime os occuring
print(a.count('o'))
print(a.count("H"))

# to convert each letter in uper case
print(a.upper())

# to convert each letter in lower case
print(a.lower())

# find the index of eany character
print(a.index("o"))
print(a.index("o",22,28))

# to covert the first letter to capilta
print(a.capitalize())

# to convert a string in to lower case
print(a.casefold())

# to find a character by index
print(a.find('o'))

# to write a variable in a string
name="jon"
age ="20"
b="my name is {},and my age is {} "
print(b.format(name,age))

# it fills the given characters and centralizes a string
print(name.center(20,"*"))

# isalnum() - Returns True if all characters in the string are alphanumeric (letters or numbers)
# isalpha() - Returns True if all characters in the string are alphabetic (only letters)
# isdecimal() - Returns True if all characters in the string are decimal numbers (0-9 only)
# isdigit() - Returns True if all characters in the string are digits (includes superscripts etc.)
# isnumeric() - Returns True if all characters are numeric (includes fractions, roman numerals, etc.)
# islower() - Returns True if all alphabetic characters in the string are lowercase
# isupper() - Returns True if all alphabetic characters in the string are uppercase
# isspace() - Returns True if all characters in the string are whitespace (space, tab, newline)
# istitle() - Returns True if the string is in title case (each word starts with a capital letter)

s = "Python3"
print(s.isalnum())  # True

s2 = "Python 3"
print(s2.isalnum())  # False (space is not alphanumeric)

s = "Python"
print(s.isalpha())  # True

s2 = "Python3"
print(s2.isalpha())  # False (contains a number)

s = "12345"
print(s.isdecimal())  # True

s2 = "12.5"
print(s2.isdecimal())  # False (decimal point not allowed)

s3 = "²"  # superscript 2
print(s3.isdecimal())  # False

s = "12345"
print(s.isdigit())  # True

s2 = "²"  # superscript 2
print(s2.isdigit())  # True

s3 = "12a"
print(s3.isdigit())  # False

s = "123"
print(s.isnumeric())  # True

s2 = "½"  # one-half fraction
print(s2.isnumeric())  # True

s3 = "abc"
print(s3.isnumeric())  # False

s = "hello"
print(s.islower())  # True

s2 = "Hello"
print(s2.islower())  # False

s = "HELLO"
print(s.isupper())  # True

s2 = "Hello"
print(s2.isupper())  # False

s = "   "
print(s.isspace())  # True

s2 = "  \n\t"
print(s2.isspace())  # True

s3 = " a "
print(s3.isspace())  # False

s = "This Is A Title"
print(s.istitle())  # True

s2 = "this Is A title"
print(s2.istitle())  # False

# endswith() - Returns True if the string ends with the specified substring
# startswith() - Returns True if the string starts with the specified substring
# swapcase() - Swaps the case of each character (lower -> upper, upper -> lower)
# strip() - Removes whitespace (or specified characters) from both ends of the string
# split() - Splits the string into a list using a separator (default is space)
# rjust() - Returns a right-justified version of the string, padded with spaces (or specified char)
# ljust() - Returns a left-justified version of the string, padded with spaces (or specified char)
# replace() - Replaces all occurrences of a substring with another substring
# rindex() - Returns the highest index of the specified substring (raises error if not found)
# rfind() - Returns the highest index of the specified substring (returns -1 if not found)

# True example
s = "hello world"
print(s.endswith("world"))  # True

# False example
print(s.endswith("hello"))  # False

# True example
s = "hello world"
print(s.startswith("hello"))  # True

# False example
print(s.startswith("world"))  # False

# Example (no True/False, just output)
s = "HeLLo WoRLd"
print(s.swapcase())  # hEllO wOrlD

s2 = "python"
print(s2.swapcase())  # PYTHON

# True example (comparing stripped string)
s = "   hello   "
print(s)
print(s.strip())
print(s.strip() == "hello")  # True

# False example
print(s.strip() == "   hello   ")  # False

# True example
s = "apple,banana,grape"
print(s.split(","))  # ['apple', 'banana', 'grape']
s = "apple#banana#grape"
print(s.split("#"))
# False example
print(s.split(",") == ["apple", "banana", "grape"])  # True

# False example
print(s.split(",") == ["apple banana grape"])  # False

# True example
s = "42"
print( "the number is ", s.rjust(5) )  # True
print( "the number is ", s.rjust(5,"*") )  # True

# True example
s = "42"
print(s.ljust(5) ,"is a number" ) # True

print(s.ljust(5,"*") ,"is a number" ) # True

# True example
s = "I like apples"
print(s.replace("apples", "bananas"))

print(s.replace("apples", "bananas") == "I like bananas")  # True

# False example
print(s.replace("apples", "bananas") == "I like apples")  # False

s = "apple banana apple"
print(s.rindex("apple"))

s = "apple banana apple"
print(s.rfind("apple") )

"""**string slicing**"""

a="Harry Potter and the Goble of Fire"
print(a)

# want to print only harry
print(a[0:5])
print(a[:5])
print(a[6:])

print(a[-3:])

b="0123456789"
print(b[::2])
print(b[:6:2])

"""# problems

**"OOTD.YOLO.ASAP.BRB.GTG.OTW"**
"""

a="OOTD.YOLO.ASAP.BRB.GTG.OTW"

"""**write a program to separat the following string into coma(,) separated values.**"""

b=a.split(".")
print(b)

"""**write a program to sort string alphabetically in python.**"""

b=sorted(a)
print(b)

"""**write a program to remove a given character from a string.**"""

b="hello"
c=b.replace("l","")
print(c)

"""**"F.R.I.E.N.D.S"**

**write a program to remove dot(.) from the following string.**
"""

Z="F.R.I.E.N.D.S"
b=Z.replace(".","")
print(b)

"""**write a program to check the number of occurrence of string in a string**"""

a="she sells sea shells by the sea shore"
b=a.count("sea")
print(b)

"""**take an input from a user as a string then, reverse it.**"""

a=input("Enter anything here: ")

b=a[::-1]
print(b)

"""**write a program too check if a string contains only digits**"""

a=input("Enter anything here: ")
b=a.isdigit()
if b==True:
  print("contain only digit ")
else:
  print("not contain only digit")

"""**write  program to check if a string is palindrome.**"""

a=input("Enter anything here: ")
b=a[::-1]
if a==b:
  print("palindrome")
else:
  print("not palindrome")

"""**write a program to find number of vowels in a string.**"""

a=input("Enter anything here: ")
count=0
for i in a:
  if i=="a" or i=="e" or i=="i" or i=="o" or i=="u" or i=="A" or i=="E" or i=="I" or i=="O" or i=="U":
    count=count+1
print("the number of vowels in the folowing string are ",count)

"""**write a program to check if every word in a string begins with a capital letter.**"""

a=input("Enter anything here: ")
b=a.istitle()
if b==True:
  print("every word in a string begins with a capital letter")
else:
  print("not every word in a string begins with a capital letter")